# .platform.app.yaml
name: app

type: "php:7.1"
build:
  flavor: composer

variables:
  env:
    # Tell Symfony to always install in production-mode.
    APP_ENV: 'prod'
    APP_DEBUG: 1

dependencies:
  nodejs:
    yarn: "*"

# The configuration of app when it is exposed to the web.
web:
  locations:
    "/":
      # The public directory of the app, relative to its root.
      root: "public"
      # The front-controller script to send non-static requests to.
      passthru: "/index.php"

disk: 2048

mounts:
  "/var/cache": "shared:files/cache"
  "/var/log": "shared:files/log"
  "/var/sessions": "shared:files/sessions"

hooks:
  build: |
    bin/console cache:clear
    yarn install
    yarn build
  deploy: |
    rm -rf var/cache/*