version: '3'
services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    network_mode: host
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    network_mode: host