version: '3.1'

services:
    php: &php-config
        image: lephare/php:7.2
        user: "1000:1000"
        volumes:
            - ./:/var/www/symfony
            - $SSH_AUTH_SOCK:/ssh-auth.sock
            - $HOME/.composer:/composer
        networks:
            - default
            - memcached
        environment:
            SSH_AUTH_SOCK: /ssh-auth.sock
            COMPOSER_HOME: /composer

    yarn:
        image: node:carbon
        user: "1000:1000"
        entrypoint: yarn
        command: install
        volumes:
            - ./:/var/www/symfony
        working_dir: /var/www/symfony

    composer:
        <<: *php-config
        command: composer install

    http:
        image: lephare/apache:2.4
        volumes:
            - .:/var/www/symfony
            - ./var/log/http:/var/log/apache2
        networks:
            - default
            - http-proxy
        environment:
            VIRTUAL_HOST: pashing.${DOCKER_HOST_SUFFIX:-local}
            DOCUMENT_ROOT: /var/www/symfony/public

networks:
    memcached:
        external:
            name: dev_memcached
    http-proxy:
        external:
            name: dev_proxy
