version: '3.1'

services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - 9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - http-proxy
    environment:
      VIRTUAL_HOST: prometheus.${DOCKER_HOST_SUFFIX:-local}

  grafana:
    image: grafana/grafana
    ports:
      - 3000
    networks:
      - http-proxy
    environment:
        VIRTUAL_HOST: grafana.${DOCKER_HOST_SUFFIX:-local}
